package com.kren;

import com.google.common.io.FileWriteMode;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static String getGreeting() {
	return "Hello world.";
    }

    public static void main(String[] args) {
	System.out.println(getGreeting());
	System.out.println(FileWriteMode.APPEND.toString());
    }
}
