package com.kren;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class AppTest {

    @Test
    void getGreeting() {
	assertEquals("Hello world.", App.getGreeting());

	System.out.println("HELLO FROM JUNIT 5 !!!!!!!!!!!!!!!");
    }

}
